#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>

"""Dump a tiny random-weight ModernBERT reference fixture for brain's
`brain-modernbert` parity test.

Runs the REAL `transformers.models.modernbert.modeling_modernbert.
ModernBertModel` (this container has torch 2.13 / transformers 5.15
installed) on a tiny fixed-seed config matching `ModernBertConfig::tiny()`
(`crates/modernbert/src/config.rs`) and a packed multi-span batch of two
different-length sequences, and dumps every weight, the input ids/spans, and
the reference (unpadded, per-sequence) hidden states as raw little-endian f32
blobs + manifest.json.

This script is resource-prep tooling: it is NEVER part of brain's build/test
path. Fixtures are NOT committed (`brain-never-commit-goldens` - see
`crates/diamond/tests/fixtures` for the same convention, 0 files under git);
copy the output into crates/modernbert/tests/fixtures/modernbert/ and it
stays there uncommitted, regenerated by whoever needs it.

Usage:
  python3 scripts/parity-dump/modernbert.py --out <scratch dir>/fixtures-modernbert
  cp <scratch dir>/fixtures-modernbert/* crates/modernbert/tests/fixtures/modernbert/

Swedish Embedded AB implements from-scratch GPU kernel ports of released
transformer checkpoints for clients who need an architecture their existing
inference stack does not cover, validated against the real reference
implementation rather than assumed. If your team needs a model brought up
this way, you can procure our services by emailing info@swedishembedded.com.
"""
import argparse
import json
import pathlib

import torch
from transformers.models.modernbert.modeling_modernbert import ModernBertConfig, ModernBertModel

SEED = 0

# Matches `ModernBertConfig::tiny()` exactly (see the module doc above): the
# derived per-side window is `local_attention / 2 = 3`, and both sequence
# lengths below (12, 9) are clearly past `2*window = 6`, so the local layers'
# window genuinely cuts off part of each span rather than covering it
# vacuously - the same off-by-2x trap Laya M1's own fixture had to avoid.
#
# Token ids 0/1/2/3 double as CLS/SEP/PAD/MASK, matching `tiny()`'s own
# token-id convention (the real 50281-50284 ids only make sense against the
# real 50368-token vocab).
CFG = ModernBertConfig(
    vocab_size=37,
    hidden_size=64,
    num_hidden_layers=4,
    num_attention_heads=4,
    intermediate_size=19,
    max_position_embeddings=64,
    global_attn_every_n_layers=2,
    local_attention=6,
    rope_parameters={
        "full_attention": {"rope_theta": 160000.0, "rope_type": "default"},
        "sliding_attention": {"rope_theta": 10000.0, "rope_type": "default"},
    },
    attention_bias=False,
    mlp_bias=False,
    norm_bias=False,
    hidden_activation="gelu",
    norm_eps=1e-5,
    cls_token_id=0,
    sep_token_id=1,
    pad_token_id=2,
    bos_token_id=0,
    eos_token_id=1,
    # The mask-and-pad-safe path (`sdpa`/`flash_attention_2`) is not always
    # available in every environment this script runs in; `eager` is exact
    # and portable, and this fixture is tiny enough that speed is moot.
    attn_implementation="eager",
)
SPANS = [12, 9]  # both > 2*window=6, and DIFFERENT lengths (packed, not padded)


def tensor_blob(t: torch.Tensor) -> bytes:
    return t.detach().contiguous().to(torch.float32).cpu().numpy().tobytes()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(SEED)
    model = ModernBertModel(CFG).eval()
    # `torch.nn.init.normal_(std=0.1)` sweep over every parameter - the
    # framework's own default init is NOT reused (can be huge-scale or
    # NaN-prone for a tiny random config). NOT `ModernBertConfig`'s own
    # `initializer_range` (0.02, what `crates/modernbert/src/init.rs` uses for
    # its own from-scratch default): measured directly (this script, one-off,
    # not committed as a test) that at std 0.02 the GeGLU chunk-order trap
    # this fixture exists to catch is numerically INVISIBLE - swapping
    # `gelu(gate)*input` for the correct `gelu(input)*gate` moved the final
    # hidden state by only ~4e-8, because GELU near zero is close enough to
    # linear (`gelu(x) ~= 0.5x`) that the op is nearly symmetric in its two
    # arguments there. At std 0.1 the same swap moves the output by ~3e-3,
    # three orders of magnitude past this fixture's parity tolerance, while
    # every hidden state stays comfortably finite (~0.6 max abs) - large
    # enough to force GELU off its linear region, nowhere near large enough
    # to blow up a 4-layer pre-LN stack.
    g = torch.Generator().manual_seed(SEED + 1)
    with torch.no_grad():
        for _name, p in model.named_parameters():
            torch.nn.init.normal_(p, std=0.1, generator=g)

    torch.manual_seed(SEED + 2)
    seqs = [torch.randint(0, CFG.vocab_size, (n,)) for n in SPANS]

    max_len = max(SPANS)
    batch = len(SPANS)
    input_ids = torch.full((batch, max_len), CFG.pad_token_id, dtype=torch.long)
    attention_mask = torch.zeros((batch, max_len))
    for i, s in enumerate(seqs):
        input_ids[i, : len(s)] = s
        attention_mask[i, : len(s)] = 1

    with torch.no_grad():
        out_t = model(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state

    manifest = {
        "model": "modernbert-tiny",
        "config": {
            "vocab": CFG.vocab_size,
            "d_model": CFG.hidden_size,
            "n_layers": CFG.num_hidden_layers,
            "n_heads": CFG.num_attention_heads,
            "d_ff": CFG.intermediate_size,
            "max_positions": CFG.max_position_embeddings,
            "eps": CFG.norm_eps,
            "layer_types": [t == "full_attention" for t in CFG.layer_types],
            "rope_theta_full": CFG.rope_parameters["full_attention"]["rope_theta"],
            "rope_theta_local": CFG.rope_parameters["sliding_attention"]["rope_theta"],
            "window": CFG.local_attention // 2,
            "cls_token_id": CFG.cls_token_id,
            "sep_token_id": CFG.sep_token_id,
            "pad_token_id": CFG.pad_token_id,
            "mask_token_id": 3,
        },
        "provenance": {
            "transformers": __import__("transformers").__version__,
            "torch": torch.__version__,
            "seed": SEED,
        },
        # Packed layout: `(row0, len)` per sequence, in the SAME order the
        # packed `ids`/`hidden` blobs below concatenate them - what
        # `crates/decide`'s own packed-span convention (which
        # `crates/modernbert` follows) calls a "spans" table.
        "spans": [[sum(SPANS[:i]), n] for i, n in enumerate(SPANS)],
        "weights": {},
        "inputs": {},
        "output": {},
    }

    def dump(section: str, name: str, t: torch.Tensor) -> None:
        blob = tensor_blob(t)
        fname = f"{section}.{name.replace('.', '_')}.f32"
        (out / fname).write_bytes(blob)
        manifest[section][name] = {"file": fname, "shape": list(t.shape)}

    # Real HF module names (`embeddings.tok_embeddings.weight`,
    # `layers.{l}.attn_norm.weight` absent for layer 0's `nn.Identity()`,
    # etc.) - the Rust test maps these to `crates/modernbert`'s own short
    # tensor-manifest names, it does not expect this file to rename them.
    for name, p in model.named_parameters():
        dump("weights", name, p)

    packed_ids = torch.cat(seqs).to(torch.float32)  # cast for the f32 blob convention
    dump("inputs", "ids", packed_ids)

    packed_hidden = torch.cat([out_t[i, : len(s)] for i, s in enumerate(seqs)], dim=0)
    dump("output", "hidden", packed_hidden)

    (out / "manifest.json").write_text(json.dumps(manifest, indent=1))
    total = sum(f.stat().st_size for f in out.iterdir())
    print(f"wrote {len(list(out.iterdir()))} files, {total / 1024:.0f} KiB -> {out}")


if __name__ == "__main__":
    main()
