#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>

"""Dump a tiny random-weight ModernBERT + Laya decision-head reference
fixture for brain's `brain-modernbert` parity tests.

Runs the REAL `transformers.models.modernbert.modeling_modernbert.
ModernBertModel` (this container has torch 2.13 / transformers 5.15
installed) on a tiny fixed-seed config matching `ModernBertConfig::tiny()`
(`crates/modernbert/src/config.rs`) and a packed multi-span batch of two
different-length sequences, and dumps every weight, the input ids/spans, and
the reference (unpadded, per-sequence) hidden states as raw little-endian f32
blobs + manifest.json.

It ALSO builds `convaiinnovations/laya`'s own `DecisionModel` wrapper
(`rl_common.py`, Apache-2.0) around that SAME tiny encoder - a small inline
copy of the class rather than a new pip dependency - runs it on a synthetic
packed batch with real marker positions and qtypes, and dumps the head's own
weights, `marker_pos`/`marker_mask`/`qtype`, and both `logits` (option
scores) and `act_logits` under the manifest's `head_weights`/`head_inputs`/
`head_output` sections, read by `crates/modernbert/tests/laya_parity.rs`.

This script is resource-prep tooling: it is NEVER part of brain's build/test
path. Fixtures are NOT committed (`brain-never-commit-goldens` - see
`crates/diamond/tests/fixtures` for the same convention, 0 files under git);
copy the output into crates/modernbert/tests/fixtures/modernbert/ and it
stays there uncommitted, regenerated by whoever needs it.

Usage:
  python3 scripts/parity-dump/modernbert.py --out <scratch dir>/fixtures-modernbert
  cp <scratch dir>/fixtures-modernbert/* crates/modernbert/tests/fixtures/modernbert/

Swedish Embedded AB implements from-scratch GPU kernel ports of released
transformer checkpoints for clients who need an architecture their existing
inference stack does not cover, validated against the real reference
implementation rather than assumed. If your team needs a model brought up
this way, you can procure our services by emailing info@swedishembedded.com.
"""
import argparse
import json
import pathlib

import torch
import torch.nn as nn
from transformers.models.modernbert.modeling_modernbert import ModernBertConfig, ModernBertModel

SEED = 0

# Matches `ModernBertConfig::tiny()` exactly (see the module doc above): the
# derived per-side window is `local_attention / 2 = 3`, and both sequence
# lengths below (12, 9) are clearly past `2*window = 6`, so the local layers'
# window genuinely cuts off part of each span rather than covering it
# vacuously - the same off-by-2x trap Laya M1's own fixture had to avoid.
#
# Token ids 0/1/2/3 double as CLS/SEP/PAD/MASK, matching `tiny()`'s own
# token-id convention (the real 50281-50284 ids only make sense against the
# real 50368-token vocab).
CFG = ModernBertConfig(
    vocab_size=37,
    hidden_size=64,
    num_hidden_layers=4,
    num_attention_heads=4,
    intermediate_size=19,
    max_position_embeddings=64,
    global_attn_every_n_layers=2,
    local_attention=6,
    rope_parameters={
        "full_attention": {"rope_theta": 160000.0, "rope_type": "default"},
        "sliding_attention": {"rope_theta": 10000.0, "rope_type": "default"},
    },
    attention_bias=False,
    mlp_bias=False,
    norm_bias=False,
    hidden_activation="gelu",
    norm_eps=1e-5,
    cls_token_id=0,
    sep_token_id=1,
    pad_token_id=2,
    bos_token_id=0,
    eos_token_id=1,
    # The mask-and-pad-safe path (`sdpa`/`flash_attention_2`) is not always
    # available in every environment this script runs in; `eager` is exact
    # and portable, and this fixture is tiny enough that speed is moot.
    attn_implementation="eager",
)
SPANS = [12, 9]  # both > 2*window=6, and DIFFERENT lengths (packed, not padded)

# Laya M3: synthetic marker layout for the decision head, over the SAME two
# packed sequences above. Front-packed (valid markers first) so a flat
# "valid options only" comparison needs no masking on the Rust side - see
# `crates/modernbert/src/laya.rs`'s own module doc on why brain never pads.
HEAD_LAYERS = 2
MAX_OPTIONS = 3
# question 0 (len 12): 3 real options; question 1 (len 9): 2 real options and
# one masked-out padding slot - different arities on purpose, the same
# `k.clamp(min=2)`/`topk(2)` edge this fixture exists to exercise.
MARKER_POS = [[2, 5, 8], [1, 4, 0]]
MARKER_MASK = [[True, True, True], [True, True, False]]
QTYPE = [0, 2]


class DecisionHead(nn.Module):
    """`convaiinnovations/laya`'s own `rl_common.DecisionModel`, minus the
    encoder (passed the encoder's hidden states directly) - an inline copy,
    not a new pip dependency, kept byte-for-byte faithful to the real module
    names (`head.layers.*`, `scorer.*`, `act_head.*`, `type_emb.*`) so the
    dumped weights need no renaming to match the real checkpoint's own.
    """

    def __init__(self, d: int, head_layers: int = HEAD_LAYERS, n_act: int = 2):
        super().__init__()
        nhead = max(1, d // 64)
        layer = nn.TransformerEncoderLayer(d, nhead, 4 * d, dropout=0.0, batch_first=True, norm_first=True)
        self.head = nn.TransformerEncoder(layer, head_layers)
        self.type_emb = nn.Embedding(3, d)
        self.scorer = nn.Sequential(nn.LayerNorm(d), nn.Linear(d, d), nn.GELU(), nn.Linear(d, 1))
        self.act_head = nn.Sequential(nn.Linear(d + 4, 256), nn.GELU(), nn.Linear(256, n_act))

    def forward(self, h, attention_mask, marker_pos, marker_mask, qtype):
        h = h + self.type_emb(qtype)[:, None, :]
        pad = ~attention_mask.bool()
        for layer in self.head.layers:
            h = layer(h, src_key_padding_mask=pad)
        idx = marker_pos.clamp(min=0)[:, :, None].expand(-1, -1, h.size(-1))
        m = torch.gather(h, 1, idx)
        logits = self.scorer(m).squeeze(-1).float()
        logits = logits.masked_fill(~marker_mask, -1e4)
        p = torch.softmax(logits.detach(), -1)
        k = marker_mask.sum(-1).clamp(min=2).float()
        ent = -(p * torch.log(p.clamp_min(1e-9))).sum(-1) / torch.log(k)
        top2 = p.topk(2, -1).values
        feats = torch.stack([top2[:, 0], top2[:, 0] - top2[:, 1], ent, k / 255.0], -1)
        pooled = h[:, 0].float()
        act_logits = self.act_head(torch.cat([pooled, feats], -1))
        return logits, act_logits


def tensor_blob(t: torch.Tensor) -> bytes:
    return t.detach().contiguous().to(torch.float32).cpu().numpy().tobytes()


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--out", required=True)
    args = ap.parse_args()
    out = pathlib.Path(args.out)
    out.mkdir(parents=True, exist_ok=True)

    torch.manual_seed(SEED)
    model = ModernBertModel(CFG).eval()
    # `torch.nn.init.normal_(std=0.1)` sweep over every parameter - the
    # framework's own default init is NOT reused (can be huge-scale or
    # NaN-prone for a tiny random config). NOT `ModernBertConfig`'s own
    # `initializer_range` (0.02, what `crates/modernbert/src/init.rs` uses for
    # its own from-scratch default): measured directly (this script, one-off,
    # not committed as a test) that at std 0.02 the GeGLU chunk-order trap
    # this fixture exists to catch is numerically INVISIBLE - swapping
    # `gelu(gate)*input` for the correct `gelu(input)*gate` moved the final
    # hidden state by only ~4e-8, because GELU near zero is close enough to
    # linear (`gelu(x) ~= 0.5x`) that the op is nearly symmetric in its two
    # arguments there. At std 0.1 the same swap moves the output by ~3e-3,
    # three orders of magnitude past this fixture's parity tolerance, while
    # every hidden state stays comfortably finite (~0.6 max abs) - large
    # enough to force GELU off its linear region, nowhere near large enough
    # to blow up a 4-layer pre-LN stack.
    g = torch.Generator().manual_seed(SEED + 1)
    with torch.no_grad():
        for _name, p in model.named_parameters():
            torch.nn.init.normal_(p, std=0.1, generator=g)

    torch.manual_seed(SEED + 2)
    seqs = [torch.randint(0, CFG.vocab_size, (n,)) for n in SPANS]

    max_len = max(SPANS)
    batch = len(SPANS)
    input_ids = torch.full((batch, max_len), CFG.pad_token_id, dtype=torch.long)
    attention_mask = torch.zeros((batch, max_len))
    for i, s in enumerate(seqs):
        input_ids[i, : len(s)] = s
        attention_mask[i, : len(s)] = 1

    with torch.no_grad():
        out_t = model(input_ids=input_ids, attention_mask=attention_mask).last_hidden_state

    manifest = {
        "model": "modernbert-tiny",
        "config": {
            "vocab": CFG.vocab_size,
            "d_model": CFG.hidden_size,
            "n_layers": CFG.num_hidden_layers,
            "n_heads": CFG.num_attention_heads,
            "d_ff": CFG.intermediate_size,
            "max_positions": CFG.max_position_embeddings,
            "eps": CFG.norm_eps,
            "layer_types": [t == "full_attention" for t in CFG.layer_types],
            "rope_theta_full": CFG.rope_parameters["full_attention"]["rope_theta"],
            "rope_theta_local": CFG.rope_parameters["sliding_attention"]["rope_theta"],
            "window": CFG.local_attention // 2,
            "cls_token_id": CFG.cls_token_id,
            "sep_token_id": CFG.sep_token_id,
            "pad_token_id": CFG.pad_token_id,
            "mask_token_id": 3,
        },
        "provenance": {
            "transformers": __import__("transformers").__version__,
            "torch": torch.__version__,
            "seed": SEED,
        },
        # Packed layout: `(row0, len)` per sequence, in the SAME order the
        # packed `ids`/`hidden` blobs below concatenate them - what
        # `crates/decide`'s own packed-span convention (which
        # `crates/modernbert` follows) calls a "spans" table.
        "spans": [[sum(SPANS[:i]), n] for i, n in enumerate(SPANS)],
        "weights": {},
        "inputs": {},
        "output": {},
        "head_weights": {},
        "head_inputs": {},
        "head_output": {},
    }

    def dump(section: str, name: str, t: torch.Tensor) -> None:
        blob = tensor_blob(t)
        fname = f"{section}.{name.replace('.', '_')}.f32"
        (out / fname).write_bytes(blob)
        manifest[section][name] = {"file": fname, "shape": list(t.shape)}

    # Real HF module names (`embeddings.tok_embeddings.weight`,
    # `layers.{l}.attn_norm.weight` absent for layer 0's `nn.Identity()`,
    # etc.) - the Rust test maps these to `crates/modernbert`'s own short
    # tensor-manifest names, it does not expect this file to rename them.
    for name, p in model.named_parameters():
        dump("weights", name, p)

    packed_ids = torch.cat(seqs).to(torch.float32)  # cast for the f32 blob convention
    dump("inputs", "ids", packed_ids)

    packed_hidden = torch.cat([out_t[i, : len(s)] for i, s in enumerate(seqs)], dim=0)
    dump("output", "hidden", packed_hidden)

    # ---- Laya M3: the decision head, wrapped around the SAME encoder ----
    head = DecisionHead(CFG.hidden_size).eval()
    # Same std=0.1 reasoning as the encoder's own init above, verified
    # empirically for the head too rather than assumed to transfer: at
    # `initializer_range` (0.02) the RELU-vs-GELU trap is not numerically
    # invisible the way the GeGLU one was (ReLU and GELU do not converge to
    # the same near-zero-input linear approximation the way `gelu(u)*v` vs
    # `gelu(v)*u` did), but 0.1 keeps one init recipe for the whole fixture
    # and stays comfortably finite through the head's own 2 layers.
    gh = torch.Generator().manual_seed(SEED + 3)
    with torch.no_grad():
        for _name, p in head.named_parameters():
            torch.nn.init.normal_(p, std=0.1, generator=gh)

    marker_pos = torch.tensor(MARKER_POS, dtype=torch.long)
    marker_mask = torch.tensor(MARKER_MASK, dtype=torch.bool)
    qtype = torch.tensor(QTYPE, dtype=torch.long)
    with torch.no_grad():
        logits, act_logits = head(out_t, attention_mask, marker_pos, marker_mask, qtype)

    for name, p in head.named_parameters():
        dump("head_weights", name, p)

    dump("head_inputs", "marker_pos", marker_pos.to(torch.float32))
    dump("head_inputs", "marker_mask", marker_mask.to(torch.float32))
    dump("head_inputs", "qtype", qtype.to(torch.float32))

    # Flat, valid-options-only, front-packed per question - the same shape
    # `LayaHead::forward` returns (see `crates/modernbert/src/laya.rs`'s own
    # module doc on why brain never computes a padded/masked entry at all).
    row0 = [sum(SPANS[:i]) for i in range(len(SPANS))]
    arity = [int(sum(row)) for row in MARKER_MASK]
    valid_logits = torch.cat([logits[b, : arity[b]] for b in range(len(SPANS))])
    marker_rows_absolute = torch.tensor(
        [row0[b] + MARKER_POS[b][j] for b in range(len(SPANS)) for j in range(arity[b])],
        dtype=torch.float32,
    )
    manifest["head_inputs"]["arity"] = arity
    dump("head_inputs", "marker_rows_absolute", marker_rows_absolute)
    dump("head_output", "logits", valid_logits)
    dump("head_output", "act_logits", act_logits)

    (out / "manifest.json").write_text(json.dumps(manifest, indent=1))
    total = sum(f.stat().st_size for f in out.iterdir())
    print(f"wrote {len(list(out.iterdir()))} files, {total / 1024:.0f} KiB -> {out}")


if __name__ == "__main__":
    main()
