// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>

//! VENDORED, generated bindings for the minimal ONNX protobuf subset.
//!
//! Generated by `prost-build` from `crates/onnx/proto/onnx.proto` and committed
//! verbatim so brain's build depends only on the `prost` runtime crate (no
//! `protoc`/codegen in the build path). Regenerate via `crates/onnx/proto/README.md`.
//!
//! Field numbers/enum values match the official `onnx.proto`, so the encoded
//! wire bytes are byte-identical to a real ONNX file.
#![allow(clippy::all)]

// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TensorShapeProto {
    #[prost(message, repeated, tag = "1")]
    pub dim: ::prost::alloc::vec::Vec<tensor_shape_proto::Dimension>,
}
/// Nested message and enum types in `TensorShapeProto`.
pub mod tensor_shape_proto {
    #[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
    pub struct Dimension {
        #[prost(int64, tag = "1")]
        pub dim_value: i64,
        #[prost(string, tag = "2")]
        pub dim_param: ::prost::alloc::string::String,
        #[prost(string, tag = "3")]
        pub denotation: ::prost::alloc::string::String,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TypeProto {
    #[prost(message, optional, tag = "1")]
    pub tensor_type: ::core::option::Option<type_proto::Tensor>,
    #[prost(string, tag = "6")]
    pub denotation: ::prost::alloc::string::String,
}
/// Nested message and enum types in `TypeProto`.
pub mod type_proto {
    #[derive(Clone, PartialEq, ::prost::Message)]
    pub struct Tensor {
        #[prost(int32, tag = "1")]
        pub elem_type: i32,
        #[prost(message, optional, tag = "2")]
        pub shape: ::core::option::Option<super::TensorShapeProto>,
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TensorProto {
    #[prost(int64, repeated, tag = "1")]
    pub dims: ::prost::alloc::vec::Vec<i64>,
    #[prost(int32, tag = "2")]
    pub data_type: i32,
    #[prost(float, repeated, tag = "4")]
    pub float_data: ::prost::alloc::vec::Vec<f32>,
    #[prost(int32, repeated, tag = "5")]
    pub int32_data: ::prost::alloc::vec::Vec<i32>,
    #[prost(int64, repeated, tag = "7")]
    pub int64_data: ::prost::alloc::vec::Vec<i64>,
    #[prost(string, tag = "8")]
    pub name: ::prost::alloc::string::String,
    #[prost(bytes = "vec", tag = "9")]
    pub raw_data: ::prost::alloc::vec::Vec<u8>,
    /// Key/value metadata for `data_location = EXTERNAL` (keys: location/offset/length).
    #[prost(message, repeated, tag = "13")]
    pub external_data: ::prost::alloc::vec::Vec<StringStringEntryProto>,
    /// 0 = DEFAULT (inline raw_data), 1 = EXTERNAL (data in a sidecar file).
    #[prost(int32, tag = "14")]
    pub data_location: i32,
}
/// ONNX `StringStringEntryProto` — a key/value string pair (a tensor's
/// `external_data` entries: location, offset, length).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct StringStringEntryProto {
    #[prost(string, tag = "1")]
    pub key: ::prost::alloc::string::String,
    #[prost(string, tag = "2")]
    pub value: ::prost::alloc::string::String,
}
/// Nested message and enum types in `TensorProto`.
pub mod tensor_proto {
    /// DataType subset (values match onnx::TensorProto::DataType).
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum DataType {
        Undefined = 0,
        Float = 1,
        Uint8 = 2,
        Int8 = 3,
        Int32 = 6,
        Int64 = 7,
    }
    impl DataType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "UNDEFINED",
                Self::Float => "FLOAT",
                Self::Uint8 => "UINT8",
                Self::Int8 => "INT8",
                Self::Int32 => "INT32",
                Self::Int64 => "INT64",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNDEFINED" => Some(Self::Undefined),
                "FLOAT" => Some(Self::Float),
                "UINT8" => Some(Self::Uint8),
                "INT8" => Some(Self::Int8),
                "INT32" => Some(Self::Int32),
                "INT64" => Some(Self::Int64),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ValueInfoProto {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "2")]
    pub r#type: ::core::option::Option<TypeProto>,
    #[prost(string, tag = "3")]
    pub doc_string: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AttributeProto {
    #[prost(string, tag = "1")]
    pub name: ::prost::alloc::string::String,
    #[prost(float, tag = "2")]
    pub f: f32,
    #[prost(int64, tag = "3")]
    pub i: i64,
    #[prost(bytes = "vec", tag = "4")]
    pub s: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag = "5")]
    pub t: ::core::option::Option<TensorProto>,
    #[prost(float, repeated, tag = "7")]
    pub floats: ::prost::alloc::vec::Vec<f32>,
    #[prost(int64, repeated, tag = "8")]
    pub ints: ::prost::alloc::vec::Vec<i64>,
    #[prost(bytes = "vec", repeated, tag = "9")]
    pub strings: ::prost::alloc::vec::Vec<::prost::alloc::vec::Vec<u8>>,
    #[prost(message, repeated, tag = "10")]
    pub tensors: ::prost::alloc::vec::Vec<TensorProto>,
    #[prost(enumeration = "attribute_proto::AttributeType", tag = "20")]
    pub r#type: i32,
    #[prost(string, tag = "13")]
    pub doc_string: ::prost::alloc::string::String,
}
/// Nested message and enum types in `AttributeProto`.
pub mod attribute_proto {
    #[derive(
        Clone,
        Copy,
        Debug,
        PartialEq,
        Eq,
        Hash,
        PartialOrd,
        Ord,
        ::prost::Enumeration
    )]
    #[repr(i32)]
    pub enum AttributeType {
        Undefined = 0,
        Float = 1,
        Int = 2,
        String = 3,
        Tensor = 4,
        Graph = 5,
        Floats = 6,
        Ints = 7,
        Strings = 8,
        Tensors = 9,
        Graphs = 10,
    }
    impl AttributeType {
        /// String value of the enum field names used in the ProtoBuf definition.
        ///
        /// The values are not transformed in any way and thus are considered stable
        /// (if the ProtoBuf definition does not change) and safe for programmatic use.
        pub fn as_str_name(&self) -> &'static str {
            match self {
                Self::Undefined => "UNDEFINED",
                Self::Float => "FLOAT",
                Self::Int => "INT",
                Self::String => "STRING",
                Self::Tensor => "TENSOR",
                Self::Graph => "GRAPH",
                Self::Floats => "FLOATS",
                Self::Ints => "INTS",
                Self::Strings => "STRINGS",
                Self::Tensors => "TENSORS",
                Self::Graphs => "GRAPHS",
            }
        }
        /// Creates an enum from field names used in the ProtoBuf definition.
        pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
            match value {
                "UNDEFINED" => Some(Self::Undefined),
                "FLOAT" => Some(Self::Float),
                "INT" => Some(Self::Int),
                "STRING" => Some(Self::String),
                "TENSOR" => Some(Self::Tensor),
                "GRAPH" => Some(Self::Graph),
                "FLOATS" => Some(Self::Floats),
                "INTS" => Some(Self::Ints),
                "STRINGS" => Some(Self::Strings),
                "TENSORS" => Some(Self::Tensors),
                "GRAPHS" => Some(Self::Graphs),
                _ => None,
            }
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct NodeProto {
    #[prost(string, repeated, tag = "1")]
    pub input: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, repeated, tag = "2")]
    pub output: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag = "3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub op_type: ::prost::alloc::string::String,
    #[prost(string, tag = "7")]
    pub domain: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub attribute: ::prost::alloc::vec::Vec<AttributeProto>,
    #[prost(string, tag = "6")]
    pub doc_string: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct GraphProto {
    #[prost(message, repeated, tag = "1")]
    pub node: ::prost::alloc::vec::Vec<NodeProto>,
    #[prost(string, tag = "2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "5")]
    pub initializer: ::prost::alloc::vec::Vec<TensorProto>,
    #[prost(string, tag = "10")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, repeated, tag = "11")]
    pub input: ::prost::alloc::vec::Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "12")]
    pub output: ::prost::alloc::vec::Vec<ValueInfoProto>,
    #[prost(message, repeated, tag = "13")]
    pub value_info: ::prost::alloc::vec::Vec<ValueInfoProto>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct OperatorSetIdProto {
    #[prost(string, tag = "1")]
    pub domain: ::prost::alloc::string::String,
    #[prost(int64, tag = "2")]
    pub version: i64,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ModelProto {
    #[prost(int64, tag = "1")]
    pub ir_version: i64,
    #[prost(message, repeated, tag = "8")]
    pub opset_import: ::prost::alloc::vec::Vec<OperatorSetIdProto>,
    #[prost(string, tag = "2")]
    pub producer_name: ::prost::alloc::string::String,
    #[prost(string, tag = "3")]
    pub producer_version: ::prost::alloc::string::String,
    #[prost(string, tag = "4")]
    pub domain: ::prost::alloc::string::String,
    #[prost(int64, tag = "5")]
    pub model_version: i64,
    #[prost(string, tag = "6")]
    pub doc_string: ::prost::alloc::string::String,
    #[prost(message, optional, tag = "7")]
    pub graph: ::core::option::Option<GraphProto>,
}
