// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>

//! Token-for-token parity between `modernbert::build_sequence` and the real
//! `convaiinnovations/laya` `rl_common.py::build_sequence` (Apache-2.0), on
//! real `(state, question)` pairs covering: a multi-key JSON state, a
//! `choice` question with several options, a `score` question, a `noul`
//! question (both default and explicit criteria text), a case that exercises
//! the `opt_budget < 16` even-shrink path (many long options), and a plain
//! string state.
//!
//! Fixtures generated by `scripts/parity-dump/laya_seq.py` against the real
//! downloaded checkpoint's tokenizer, calling the real (vendored, Apache-2.0)
//! `build_sequence` directly - not committed (`crates/modernbert/tests/
//! fixtures/` is entirely gitignored, same convention as every other
//! `scripts/parity-dump/*.py` fixture in this crate). Regenerate with:
//!
//! ```text
//! python3 scripts/parity-dump/laya_seq.py --dir ~/.local/share/brain/models/convaiinnovations/laya \
//!     --out <scratch>/fixtures-laya-seq
//! cp <scratch>/fixtures-laya-seq/manifest.json crates/modernbert/tests/fixtures/laya_seq/
//! ```
//!
//! `state`/`question.crit` are stored in the fixture using a `{"__obj__":
//! [[k, v], ...]}` tag rather than a plain JSON object - see
//! `modernbert::sequence`'s own module doc for why (this workspace's
//! `serde_json` does not preserve object key order, but `build_sequence`'s
//! own correctness genuinely depends on it for a multi-key state).

use modernbert::{OrderedJson, QType, Question, State};

fn fixture_dir() -> std::path::PathBuf {
    if let Ok(d) = std::env::var("MODERNBERT_SEQ_FIXTURE_DIR") {
        return std::path::PathBuf::from(d);
    }
    std::path::Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures/laya_seq")
}

/// Reconstruct an [`OrderedJson`] from the fixture's `{"__obj__": [[k,v],...]}`
/// tagged encoding - see the module doc.
fn parse_ordered(v: &serde_json::Value) -> OrderedJson {
    match v {
        serde_json::Value::Null => OrderedJson::Null,
        serde_json::Value::Bool(b) => OrderedJson::Bool(*b),
        serde_json::Value::Number(n) => OrderedJson::Number(n.clone()),
        serde_json::Value::String(s) => OrderedJson::String(s.clone()),
        serde_json::Value::Array(items) => OrderedJson::Array(items.iter().map(parse_ordered).collect()),
        serde_json::Value::Object(map) => {
            let pairs = map
                .get("__obj__")
                .and_then(|p| p.as_array())
                .unwrap_or_else(|| panic!("fixture: expected {{\"__obj__\": [...]}} tag, got {v}"));
            let entries = pairs
                .iter()
                .map(|pair| {
                    let a = pair.as_array().expect("__obj__ entry must be a [key, value] pair");
                    let k = a[0].as_str().expect("__obj__ key must be a string").to_string();
                    (k, parse_ordered(&a[1]))
                })
                .collect();
            OrderedJson::Object(entries)
        }
    }
}

fn state_from_fixture(v: &serde_json::Value) -> State {
    match v {
        serde_json::Value::String(s) => State::Str(s.clone()),
        other => State::Json(parse_ordered(other)),
    }
}

fn question_from_fixture(v: &serde_json::Value) -> Question {
    let t = v["t"].as_str().expect("question.t");
    let ins = v["ins"].as_str().expect("question.ins").to_string();
    let crit = parse_ordered(&v["crit"]);
    match t {
        "choice" => {
            let entries = match crit {
                OrderedJson::Object(e) => e,
                OrderedJson::Null => Vec::new(),
                other => panic!("choice crit must be an object, got {other:?}"),
            };
            let options = entries
                .into_iter()
                .map(|(k, v)| {
                    let desc = match v {
                        OrderedJson::String(s) => Some(s),
                        OrderedJson::Null => None,
                        other => panic!("choice option value must be string or null, got {other:?}"),
                    };
                    (k, desc)
                })
                .collect();
            Question::Choice { ins, options }
        }
        "score" => {
            let items = match crit {
                OrderedJson::Array(a) => a,
                other => panic!("score crit must be an array, got {other:?}"),
            };
            let options = items
                .into_iter()
                .map(|v| match v {
                    OrderedJson::String(s) => s,
                    other => panic!("score crit item must be a string, got {other:?}"),
                })
                .collect();
            Question::Score { ins, options }
        }
        "noul" => {
            let mut false_text = None;
            let mut true_text = None;
            if let OrderedJson::Object(entries) = crit {
                for (k, v) in entries {
                    let s = match v {
                        OrderedJson::String(s) => Some(s),
                        _ => None,
                    };
                    match k.as_str() {
                        "false" => false_text = s,
                        "true" => true_text = s,
                        _ => {}
                    }
                }
            }
            Question::Noul { ins, false_text, true_text }
        }
        other => panic!("unknown question type {other:?}"),
    }
}

#[test]
fn build_sequence_matches_the_real_python_reference() {
    let dir = fixture_dir();
    let manifest_path = dir.join("manifest.json");
    if !manifest_path.exists() {
        brain_testutil::skip(&format!(
            "{} absent - run `python3 scripts/parity-dump/laya_seq.py --dir <checkpoint dir> --out <scratch>` \
             and copy manifest.json into {}",
            manifest_path.display(),
            dir.display()
        ));
        return;
    }
    let manifest: serde_json::Value = serde_json::from_str(&std::fs::read_to_string(&manifest_path).unwrap()).unwrap();

    let tok_dir = brain_testutil::model_dir("convaiinnovations/laya");
    let tok_path = tok_dir.map(|d| format!("{d}/tokenizer/tokenizer.json")).filter(|p| std::path::Path::new(p).exists());
    let Some(tok_path) = tok_path else {
        brain_testutil::skip("checkpoint tokenizer absent - run `brain pull convaiinnovations/laya`");
        return;
    };
    let tok = data::qwen_tokenizer::QwenBpe::from_file(&tok_path).expect("load Laya tokenizer.json");

    // cfg only needs the special-token ids build_sequence reads; read them
    // straight from the real tokenizer the same way modernbert::import_dir
    // does, rather than hardcoding.
    let mut cfg = modernbert::ModernBertConfig::tiny();
    cfg.cls_token_id = tok.special_id("[CLS]").expect("[CLS]");
    cfg.sep_token_id = tok.special_id("[SEP]").expect("[SEP]");
    cfg.pad_token_id = tok.special_id("[PAD]").expect("[PAD]");
    cfg.mask_token_id = tok.special_id("[MASK]").expect("[MASK]");

    let cases = manifest["build_sequence_cases"].as_array().expect("build_sequence_cases");
    assert!(!cases.is_empty());
    for case in cases {
        let name = case["name"].as_str().unwrap();
        let state = state_from_fixture(&case["state"]);
        let q = question_from_fixture(&case["question"]);
        let max_len = case["max_len"].as_u64().unwrap() as u32;
        let head_max_len = case["head_max_len"].as_u64().unwrap() as u32;
        let want_ids: Vec<u32> = case["ids"].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as u32).collect();
        let want_markers: Vec<usize> = case["markers"].as_array().unwrap().iter().map(|v| v.as_u64().unwrap() as usize).collect();

        let (got_ids, got_markers) = modernbert::build_sequence(&tok, &cfg, &state, &q, max_len, head_max_len, None, false);
        assert_eq!(got_ids, want_ids, "case {name}: ids");
        assert_eq!(got_markers, want_markers, "case {name}: markers");
        assert_eq!(got_markers.len(), q.render_options().len(), "case {name}: every option must get a marker (nothing was truncated away)");
    }
}

#[test]
fn qtype_index_matches_rl_common_pys_qtypes() {
    assert_eq!(QType::Choice.index(), 0);
    assert_eq!(QType::Score.index(), 1);
    assert_eq!(QType::Noul.index(), 2);
}
