#!/usr/bin/env python3
# SPDX-License-Identifier: Apache-2.0
# Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>

"""Dump a FastVLM-0.5B image-captioning reference so brain's decoder can produce
the SAME caption from the SAME image embeddings.

The vision tower (mobileclip) is run in HF (brain's own FastViTHD still needs SE +
head-proj + reparam import to reach feature parity), and its 256 image embeddings
are dumped. The caption is then generated by the *exact* operation brain performs:
embed the tokens, overwrite the 256 image rows with the image embeddings, run the
Qwen2 decoder, argmax — no sampling/penalties — so brain can match token-for-token.

Outputs (little-endian):
  parity/fastvlm_cap_embeds.bin  [256, 896] f32 image embeddings
  parity/fastvlm_cap_layout.bin  [2] i32: pre_len, post_len
  parity/fastvlm_cap_ids.bin     [pre_len + post_len] i32 the text token ids
  parity/fastvlm_cap_gen.bin     [G] i32 the greedy caption tokens
"""
import os

os.environ["HF_HUB_OFFLINE"] = "1"
os.environ["TRANSFORMERS_OFFLINE"] = "1"
import numpy as np
import torch
from PIL import Image
from transformers import AutoModelForCausalLM, AutoTokenizer

CKPT = "/data/workspace/resources/vl/fastvlm/hf/FastVLM-0.5B"
IMG = "/data/workspace/resources/emulation/dosbox-x/DOSBox-Logo-2-680x350.png"
OUT = "/data/workspace/resources/vl/parity"
os.makedirs(OUT, exist_ok=True)
GEN = 20

m = AutoModelForCausalLM.from_pretrained(CKPT, trust_remote_code=True, dtype=torch.float32, low_cpu_mem_usage=True).eval()
tok = AutoTokenizer.from_pretrained(CKPT)
ip = m.get_vision_tower().image_processor
eos = m.config.eos_token_id

px = ip(Image.open(IMG).convert("RGB"), return_tensors="pt")["pixel_values"].float()
with torch.no_grad():
    img_embeds = m.encode_images(px)[0]  # [256, 896]

pre = tok("<|im_start|>user\n", add_special_tokens=False).input_ids
post = tok("\nDescribe this image in one sentence.<|im_end|>\n<|im_start|>assistant\n", add_special_tokens=False).input_ids
img_start = len(pre)
emb_tab = m.get_model().embed_tokens.weight  # [vocab, 896]

def logits_from(full_ids):
    e = emb_tab[torch.tensor(full_ids)].clone()[None]  # [1, T, 896]
    e[0, img_start : img_start + 256] = img_embeds
    h = m.model(inputs_embeds=e).last_hidden_state  # [1, T, 896]
    return m.lm_head(h)[0, -1]  # [vocab]

full = pre + [0] * 256 + post  # 0 = placeholder (overwritten by the splice)
gen = []
with torch.no_grad():
    for _ in range(GEN):
        nxt = int(logits_from(full + gen).argmax())
        gen.append(nxt)
        if nxt == eos:
            break

img_embeds.detach().numpy().astype("<f4").tofile(f"{OUT}/fastvlm_cap_embeds.bin")
np.array([len(pre), len(post)], dtype="<i4").tofile(f"{OUT}/fastvlm_cap_layout.bin")
np.array(pre + post, dtype="<i4").tofile(f"{OUT}/fastvlm_cap_ids.bin")
np.array(gen, dtype="<i4").tofile(f"{OUT}/fastvlm_cap_gen.bin")
print(f"image embeds {tuple(img_embeds.shape)}, caption ({len(gen)} tok): {tok.decode(gen)!r}")
