// SPDX-License-Identifier: Apache-2.0
// Copyright (c) 2026 Martin Schröder <info@swedishembedded.com>

//! torch-bicubic parity for the pos-embed interpolation path
//! (align_corners=False, antialias=True, a=-0.75), vs refs generated by
//! torch in the scratchpad (env-gated) — plus an identity sanity check.

use mirror::preprocess::resize_bicubic_torch;

fn read_npy(path: &str) -> (Vec<usize>, Vec<f32>) {
    let b = std::fs::read(path).unwrap();
    // minimal NPY v1 parser: magic(6) ver(2) hlen(2) header
    let hlen = u16::from_le_bytes([b[8], b[9]]) as usize;
    let hdr = std::str::from_utf8(&b[10..10 + hlen]).unwrap();
    let shape_s = hdr.split("'shape': (").nth(1).unwrap().split(')').next().unwrap();
    let shape: Vec<usize> =
        shape_s.split(',').filter_map(|t| t.trim().parse().ok()).collect();
    let data = &b[10 + hlen..];
    (shape, data.chunks_exact(4).map(|c| f32::from_le_bytes([c[0], c[1], c[2], c[3]])).collect())
}

#[test]
fn identity_resize_is_exact() {
    let x: Vec<f32> = (0..3 * 5 * 7).map(|i| (i as f32 * 0.37).sin()).collect();
    let y = resize_bicubic_torch(&x, 3, 5, 7, 5, 7);
    for (a, b) in x.iter().zip(&y) {
        assert!((a - b).abs() < 1e-6);
    }
}

#[test]
fn matches_torch_refs() {
    let Ok(dir) = std::env::var("MIRROR_BICUBIC_REFS") else {
        eprintln!("MIRROR_BICUBIC_REFS not set — skipping");
        return;
    };
    let (_, x) = read_npy(&format!("{dir}/bicubic_in.npy"));
    for (name, oh, ow) in [("bicubic_out.npy", 28usize, 37usize), ("bicubic_out2.npy", 42, 30)] {
        let (shape, want) = read_npy(&format!("{dir}/{name}"));
        assert_eq!(&shape[2..], &[oh, ow]);
        let got = resize_bicubic_torch(&x, 3, 37, 37, oh, ow);
        let mut worst = 0.0f32;
        for (a, b) in got.iter().zip(&want) {
            worst = worst.max((a - b).abs());
        }
        assert!(worst < 1e-5, "{name}: worst abs diff {worst}");
    }
}
